classdef DataFindROIsFLIKA_2p5D < DataFindROIsFLIKA
%DataFindROIsFLIKA - Data from FLIKA-based ROI identification
%
%   The DataFindROIsFLIKA class contains the data generated by
%   CalcFindROIsFLIKA.
%
% DataFindROIsFLIKA_2p5D public properties inherited from Data:
%   mask            - A mask combining all of the other masks
%   means           - A helper structure containing means of the data
%   nPlotsGood      - The number of plots in non-debug mode        
%   nPlotsDebug     - The number of plots in debug mode
%   state           - The current state
%   stdevs          - A helper structure containing stdevs of the data
%
% DataFindROIsFLIKA_2p5D public properties:
%   area            - The ROI areas [µm^2]
%   blackLevel      - The calculated image black level
%   baselineAverage - A Z-projection image of the baseline period 
%   centroidT       - The ROI centroids in the t direction [frame indices]
%   centroidX       - The ROI centroids in the x direction [pixel indices]
%   centroidY       - The ROI centroids in the y direction [pixel indices]
%   duration        - The ROI durations [s]
%   puffGroupMask   - Stage 2 ROI mask (grouped regions)
%   puffPixelMask   - Stage 1 ROI mask (individual pixels)
%   puffSignificantMask - Stage 3 ROI mask (significant regions)
%   roiIdxs         - The linear pixel indices for all ROIs
%   roiMask         - The identified ROIs
%   roiNames        - The ROI names
%   volume          - The ROI volumes [µm^2 s]
%
% DataFindROIsFLIKA_2p5D public methods:
%   add_raw_data    - Add raw data to the Data object
%   add_processed_data - Add processed data to the Data object
%   add_mask_data   - Add mask data to the Data object
%   plot            - Plot a single graph from the data object
%   plot_graphs     - Plot multiple graphs from the data object
%   output_data     - Output the data
%
%   See also DataFindROIsFLIKA_2D, DataFindROIsFLIKA_3D, DataFindROIsFLIKA,
%   DataFindROIs, Data, CalcFindROIsFLIKA_2p5D, CellScan

%   Copyright (C) 2017  Matthew J.P. Barrett, Kim David Ferrari et al.
%
%   This program is free software: you can redistribute it and/or modify
%   it under the terms of the GNU General Public License as published by
%   the Free Software Foundation, either version 3 of the License, or
%   (at your option) any later version.
% 
%   This program is distributed in the hope that it will be useful,
%   but WITHOUT ANY WARRANTY; without even the implied warranty of
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%   GNU General Public License for more details.
%   
%   You should have received a copy of the GNU General Public License 
%   along with this program.  If not, see <http://www.gnu.org/licenses/>.
    
    % ================================================================== %
    
    properties
        
        %raw data
        
        %processed data
        
        %centroidT - The ROI centroids in the t direction [frame indices]
        %
        %   The t direction is counted from the first frame of the image.
        %
        %   See also DataFindROIs.centroidX, DataFindROIs.centroidY
        centroidT
        
        %duration - The ROI durations [s]
        %
        %   A cell vector of the ROI durations, calculated by dividing the
        %   number of frames that the ROI exists in by the frame rate
        %   stored in the metadata.
        %
        %   See also Metadata.frameRate
        duration

        %volume - The ROI volumes [µm^2 s]
        %
        %   The volume is calculated by multiplying the ROI volume in
        %   pixels by the physical pixel size and dividing by the frame
        %   rate stored in the metadata.
        %
        %   See also Metadata.pixelSize, Metadata.frameRate, Metadata.zoom,
        %   CalibrationPixelSize
        volume
        
        % mask data
        
    end
    
    % ------------------------------------------------------------------ %
    
    properties (Constant, Access = protected)
        
        %listRaw - Constant, protected property containing a list of
        %   raw data property names.
        listRaw = {'blackLevel', 'baselineAverage', 'puffGroupMask', ...
            'puffPixelMask'};
        
        %listProcessed - Constant, protected property containing a list of
        %   processed data property names.
        listProcessed = {'area', 'centroidT', 'centroidX', 'centroidY', ...
            'duration', 'puffSignificantMask', 'roiIdxs', 'roiMask', ...
            'roiNames', 'volume'};
        
        %listMask - Constant, protected property containing a list of
        %   mask data property names.
        listMask = {};
        
        %listPlotDebug - Constant, protected property containing a list of
        %   property names to be used for plotting when in debugging mode.
        listPlotDebug = {};
        
        %labelPlotDebug - Constant, protected property containing a list of
        %   labels to be used for plotting when in debugging mode.
        labelPlotDebug = {};
        
        %listPlotGood - Constant, protected property containing a list of
        %   property names to be used for standard plotting.
        listPlotGood = {};
        
        %labelPlotGood - Constant, protected property containing a list of
        %   labels to be used for standard plotting.
        labelPlotGood = {};
        
        %listMean - Constant, protected property containing a list of
        %   property names to be used to calculate the mean from.
        %
        %   See also Data.means
        listMean = {};
        
        %listOutput - Constant, protected property containing a list of
        %   property names, which can be written to the output CSV file.
        %
        %   See also Data.output_data
        listOutput = {'roiNames', 'area', 'centroidX', 'centroidY', ...
            'centroidT', 'duration', 'volume'};
        
        %nameDataClass - Constant, protected property containing a
        %   label, which identifies the original Data class and will be
        %   written to the output CSV file.
        %
        %   See also Data.output_data
        nameDataClass = 'ROIs Location (2.5D FLIKA)';
        
        %suffixDataClass - Constant, protected property containing a
        %   label, which will be added to the output CSV filename.
        %
        %   See also Data.output_data
        suffixDataClass = 'roiLocation2p5DFLIKA';
        
    end
    
    % ================================================================== %
    
    methods
        
        function self = set.centroidT(self, val)
            
            % Check property is a vector containing real numerics
            utils.checks.vector(val, 'centroidT')
            maskNotNaNInf = ~isnan(val) & ~isinf(val);
            utils.checks.real_num(val(maskNotNaNInf), 'centroidT')
            
            % Assign property
            self.centroidT = val(:);
        end
        
        % -------------------------------------------------------------- %
        
        function self = set.duration(self, val)
            
            % Check property is a vector containing real numerics
            utils.checks.real_num(val, 'duration')
            utils.checks.vector(val, 'duration')
            
            % Assign property
            self.duration = val(:);
        end
        
        % -------------------------------------------------------------- %
        
        function self = set.volume(self, val)
            
            % Check property is a vector containing real numerics
            utils.checks.real_num(val, 'volume')
            utils.checks.vector(val, 'volume')
            
            % Assign property
            self.volume = val(:);
        end
        
    end
    
    % ================================================================== %
    
end

