classdef (Abstract) DataDetectSigs < Data
%DataDetectSigs - Superclass for DataDetectSigs classes
%
%   The DataDetectSigs class is an abstract superclass that implements (or
%   requires implementation in its subclasses via abstract methods or
%   properties) all basic functionality related to storing data from signal
%   detection. Typically there is one concrete subclass of DataDetectSigs
%   for every concrete subclass of CalcDetectSigs, and the DataDetectSigs
%   object stores the algorithm-specific output data that is generated by
%   the corresponding CalcDetectSigs class.
%
% DataDetectSigs public properties inherited from Data:
%   mask            - A mask combining all of the other masks
%   means           - A helper structure containing means of the data
%   nPlotsGood      - The number of plots in non-debug mode        
%   nPlotsDebug     - The number of plots in debug mode
%   state           - The current state
%   stdevs          - A helper structure containing stdevs of the data
%
% DataDetectSigs public properties
%   roiName         - The ROI name
%
% DataDetectSigs public methods:
%   add_raw_data    - Add raw data to the Data object
%   add_processed_data - Add processed data to the Data object
%   add_mask_data   - Add mask data to the Data object
%   plot            - Plot a single graph from the data object
%   plot_graphs     - Plot multiple graphs from the data object
%   output_data     - Output the data
%
%   See also DataDetectSigsDummy, DataDetectSigsClsfy, Data,
%   CalcDetectSigs, CellScan

%   Copyright (C) 2017  Matthew J.P. Barrett, Kim David Ferrari et al.
%
%   This program is free software: you can redistribute it and/or modify
%   it under the terms of the GNU General Public License as published by
%   the Free Software Foundation, either version 3 of the License, or
%   (at your option) any later version.
% 
%   This program is distributed in the hope that it will be useful,
%   but WITHOUT ANY WARRANTY; without even the implied warranty of
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%   GNU General Public License for more details.
%   
%   You should have received a copy of the GNU General Public License 
%   along with this program.  If not, see <http://www.gnu.org/licenses/>.
    
    % ================================================================== %
    
    properties
        
        %roiName - The ROI name
        %
        %   A cell vector containing the ROI name corresponding to the
        %   signal.  The names are either sequential numbers or, in case of
        %   hand-clicked ROIs, as specified in ImageJ.
        %
        %   See also CalcFindROIs
        roiName

    end
    
    % ================================================================== %
    
    methods
                
        function self = set.roiName(self, val)
            
            % Check property is a cell array
            utils.checks.cell_array(val, 'roiName')
            
            % Check property is a vector
            utils.checks.vector(val, 'roiName')
            
            % Assign property
            self.roiName = val;
        end
        
    end
    
    % ================================================================== %
        
end

